spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:conference-room
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

conference-room:
  room-details:
    - 
      name: Amaze
      size: 3
    - 
      name: Beauty
      size: 7
    - 
      name: Inspire
      size: 12
    - 
      name: Strive
      size: 20
  maintenance-periods:
    -
      startTime: "09:00"
      endTime: "09:15"
    -
      startTime: "13:00"
      endTime: "13:15"
    -
      startTime: "17:00"
      endTime: "17:15"